### ISSUE TITLE
Subtitle downloader plugin fails to load

### ISSUE THREAD

**Issue by memeplex** [linuxmint/xplayer#109]
```
~:: uname -a
Linux carlos 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux
~:: xplayer --version
xplayer 1.8.2

```

It fails at startup with this error:

```
(xplayer:2258): libpeas-WARNING **: 15:05:35.588: Error importing plugin 'opensubtitles':
Traceback (most recent call last):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/xplayer/plugins/opensubtitles/opensubtitles.py", line 8, in <module>
    import xdg.BaseDirectory
ImportError: No module named xdg.BaseDirectory
```

**Comment by memeplex** [comment]
Well, it seems to me it's a package dependency issue, they forgot to add python2-xdg. Will report this to the packager. Sorry.
