### ISSUE TITLE
xplayer frezes when using "Download Movie Subtitles"

### ISSUE THREAD

**Issue by ndias** [linuxmint/xplayer#114]
When using the download movie subtitles, I can search and I get the result but when I select the subtitles and press "play with subtitles" the player frezes.

$ rpm -q xplayer
xplayer-1.8.3-1.fc28.x86_64

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/xplayer/plugins/opensubtitles/opensubtitles.py", line 210, in run
    self._message) = self._model.download_subtitles (self._subtitle_id)
  File "/usr/lib64/xplayer/plugins/opensubtitles/opensubtitles.py", line 359, in download_subtitles
    import StringIO, gzip, base64
ModuleNotFoundError: No module named 'StringIO'

From a search it seams StringIO is no available in python 3 as module
"The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively."

**Comment by ndias** [comment]
Yes, the new build works.

Thanks
