### ISSUE TITLE
gstreamer v1.16.0 update kills xplayer

### ISSUE THREAD

**Issue by schinfo** [linuxmint/xplayer#147]
```
 * Xplayer version 2.0.2
 * Distribution - Manjaro Cinnamon
```

**Issue**
After an update to gstreamer v1.16.0 xplayer closed when you try to play a video

![Bildschirmfoto vom 2019-04-26 23-52-45](https://user-images.githubusercontent.com/26834276/56838896-383af000-6880-11e9-8976-a7585e5b56e8.png)

**Steps to reproduce**
Install the updates

**Comment by leigh123linux** [comment]
Try getting the arch maintainer to rebuild xplayer against the new gstreamer1 version, failing that you might as well close the issue as you provide no debugging at all.

**Comment by oberon-manjaro** [comment]
You grumpy reply does not really give the impression that you are at all interested in keeping your software working with current libraries. I'd have assumed you could aswell ask and instruct users on how the get helpful information instead of offending them
Actually **xplayer** has already been rebuild for Manjaro and coredumps when you try to play a video:
```
(gdb) bt
#0  0x00007ffff6a8a648 in gst_tag_list_get_value_index () at /usr/lib/libgstreamer-1.0.so.0
#1  0x00007ffff6a8a791 in gst_tag_list_get_string_index () at /usr/lib/libgstreamer-1.0.so.0
#2  0x00007ffff7f6e0f8 in  () at /usr/lib/libxplayer.so.0
#3  0x00007ffff7f6e3df in bacon_video_widget_set_subtitle () at /usr/lib/libxplayer.so.0
#4  0x00007ffff7f6e512 in bacon_video_widget_set_text_subtitle () at /usr/lib/libxplayer.so.0
#5  0x00007ffff7f4b325 in xplayer_action_set_mrl_with_warning () at /usr/lib/libxplayer.so.0
#6  0x00007ffff7f4b7b9 in xplayer_action_set_mrl_and_play () at /usr/lib/libxplayer.so.0
#7  0x00007ffff7f4ba4f in  () at /usr/lib/libxplayer.so.0
#8  0x00007ffff71f1e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff71defd5 in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff71e31ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff71e4080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff7f53b0d in  () at /usr/lib/libxplayer.so.0
#13 0x00007ffff7f53fb1 in  () at /usr/lib/libxplayer.so.0
#14 0x00007ffff7300079 in g_simple_async_result_complete () at /usr/lib/libgio-2.0.so.0
#15 0x00007ffff730045a in  () at /usr/lib/libgio-2.0.so.0
#16 0x00007ffff7104661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff7106739 in  () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff710677e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff72bef5e in g_application_run () at /usr/lib/libgio-2.0.so.0
#20 0x00005555555566c8 in  ()
#21 0x00007fffffffdf38 in  ()
#22 0x0000000255556740 in  ()
#23 0x0000000000000000 in  ()
```

**Comment by leigh123linux** [comment]
xplayer-2.0.2 works fine here with gstreamer1-1.16.0, your issue is
caused by your distro's failure to rebuild their xplayer package against
the new gstreamer1 ABI.

Your issue should be filed at Manjaro bug tracker not Mints.

**Comment by oberon-manjaro** [comment]
This IS a fresh rebuild against **gstreamer 1.16.0**.

**Comment by leigh123linux** [comment]
@oberon-manjaro  If you want the issue reopened you will need to provide a backtrace with all the debug symbols present.

![Screenshot from 2019-04-27 09-18-04](https://user-images.githubusercontent.com/1299302/56846965-6397fc00-68cd-11e9-84b3-292279b3351f.png)

**Comment by oberon-manjaro** [comment]
I have other things to do and I'm generally not using xplayer anyway. I will just no longer package it for Manjaro. Thank you.

**Comment by jonathonf** [comment]
This could have been handled better.

@leigh123linux Thanks for your efforts to date.

Here's a full `gdb` run with backtrace with debug symbols:

```
(gdb) run
Starting program: /usr/bin/xplayer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff035b700 (LWP 22930)]
[New Thread 0x7fffefb5a700 (LWP 22931)]
[New Thread 0x7fffef33c700 (LWP 22932)]

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkButton does not have a child property called expand

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkButton does not have a child property called fill

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkButton does not have a child property called position

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkToggleButton does not have a child property called expand

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkToggleButton does not have a child property called fill

(xplayer:22919): Gtk-WARNING **: 15:25:47.136: GtkToggleButton does not have a child property called position
[New Thread 0x7fffde07f700 (LWP 22934)]

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'continue_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'load_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'save_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'goto_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'remove_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'add_button_clicked_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'tree_view_button_press_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'tree_view_key_press_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'tree_view_row_activated_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'tree_view_popup_menu_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'popup_goto_action_cb'.  Did you compile with -rdynamic?

(xplayer:22919): Gtk-WARNING **: 15:25:47.819: Could not find signal handler 'popup_remove_action_cb'.  Did you compile with -rdynamic?
[New Thread 0x7fffdd0b5700 (LWP 22953)]
[New Thread 0x7fffdc8b4700 (LWP 22954)]
[Thread 0x7fffdd0b5700 (LWP 22953) exited]
[Thread 0x7fffde07f700 (LWP 22934) exited]
[New Thread 0x7fffde07f700 (LWP 22956)]
[Thread 0x7fffde07f700 (LWP 22956) exited]
[New Thread 0x7fffde07f700 (LWP 22957)]
[New Thread 0x7fffdd0b5700 (LWP 22958)]

Thread 1 "xplayer" received signal SIGSEGV, Segmentation fault.
0x00007ffff6a86648 in gst_tag_list_get_value_index () from /usr/lib/libgstreamer-1.0.so.0
(gdb) bt full
#0  0x00007ffff6a86648 in gst_tag_list_get_value_index () at /usr/lib/libgstreamer-1.0.so.0
#1  0x00007ffff6a86791 in gst_tag_list_get_string_index () at /usr/lib/libgstreamer-1.0.so.0
#2  0x00007ffff7f63709 in update_orientation_from_video (bvw=0x5555561bc3a0) at bacon-video-widget.c:1718
        rotation = BVW_ROTATION_R_ZERO
        orientation_str = 0x0
        ret = <optimized out>
        angle = <optimized out>
        cache = <optimized out>
        result = 0x0
        __func__ = "bvw_update_tags"
#3  0x00007ffff7f63709 in bvw_update_tags (bvw=bvw@entry=0x5555561bc3a0, tag_list=0x0, type=<optimized out>, type@entry=0x7ffff7f7155e "text") at bacon-video-widget.c:1775
        cache = <optimized out>
        result = 0x0
        __func__ = "bvw_update_tags"
#4  0x00007ffff7f639f2 in bacon_video_widget_set_subtitle (bvw=bvw@entry=0x5555561bc3a0, subtitle=<optimized out>, subtitle@entry=0) at bacon-video-widget.c:2832
        tags = 0x0
        flags = 1687
        __FUNCTION__ = "bacon_video_widget_set_subtitle"
#5  0x00007ffff7f63b26 in bacon_video_widget_set_text_subtitle (bvw=0x5555561bc3a0, subtitle_uri=subtitle_uri@entry=0x0) at bacon-video-widget.c:3842
        cur_state = 21845
        __FUNCTION__ = "bacon_video_widget_set_text_subtitle"
        __func__ = "bacon_video_widget_set_text_subtitle"
#6  0x00007ffff7f3f564 in xplayer_action_set_mrl_with_warning
    (xplayer=xplayer@entry=0x5555555ae1a0, mrl=mrl@entry=0x555556bad600 "file:///video.mkv", subtitle=<optimized out>, warn=warn@entry=1) at xplayer-object.c:1877
        volume = <optimized out>
        autoload_sub = 0x0
        window_state = <optimized out>
        source_table = {{target = 0x7ffff7f6b42e "text/uri-list", flags = 0, info = 0}}
        caps = <optimized out>
        user_agent = 0x0
        retval = 1
#7  0x00007ffff7f3fa2b in xplayer_action_set_mrl
    (xplayer=xplayer@entry=0x5555555ae1a0, mrl=mrl@entry=0x555556bad600 "file:///video.mkv", subtitle=<optimized out>)
    at xplayer-object.c:1946
#8  0x00007ffff7f3fa3a in xplayer_action_set_mrl_and_play
    (xplayer=xplayer@entry=0x5555555ae1a0, mrl=mrl@entry=0x555556bad600 "file:///video.mkv", subtitle=<optimized out>)
    at xplayer-object.c:1313
#9  0x00007ffff7f3fcf8 in playlist_changed_cb (playlist=<optimized out>, xplayer=0x5555555ae1a0) at xplayer-object.c:3320
        mrl = 0x555556bad600 "file:///video.mkv"
        subtitle = 0x0
#10 0x00007ffff71ede75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff71dafd5 in  () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff71df1ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff71e0080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff7f483ac in xplayer_playlist_add_one_mrl (playlist=0x555555f926f0, mrl=<optimized out>, display_name=0x0, content_type=0x0) at xplayer-playlist.c:1828
        store = 0x555555f615b0
        iter = {stamp = -2003350026, user_data = 0x555556ade990, user_data2 = 0x0, user_data3 = 0x7ffff72fd241 <g_simple_async_result_propagate_error+65>}
        filename_for_display = 0x555556aa92f0 "\020\001"
        uri = <optimized out>
        escaped_filename = 0x5555563a8f60 "P\226\265VUU"
        ref = 0x0
        monitor = 0x555556320780
        mount = 0x0
        file = <optimized out>
        pos = 2147483647
        __FUNCTION__ = "xplayer_playlist_add_one_mrl"
#15 0x00007ffff7f48889 in add_mrls_cb (parser=<optimized out>, result=<optimized out>, mrl_data=0x555556bb2f30) at xplayer-playlist.c:2071
        i = <optimized out>
        operation_data = 0x555556a35040
        __FUNCTION__ = "add_mrls_cb"
#16 0x00007ffff72fc079 in g_simple_async_result_complete () at /usr/lib/libgio-2.0.so.0
#17 0x00007ffff72fc45a in  () at /usr/lib/libgio-2.0.so.0
#18 0x00007ffff7100661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff7102739 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff710277e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff72baf5e in g_application_run () at /usr/lib/libgio-2.0.so.0
#22 0x00005555555561be in main (argc=<optimized out>, argv=<optimized out>) at xplayer.c:284
        xplayer = 0x5555555ae1a0
```

**Comment by leigh123linux** [comment]
@jonathonf Thank you for providing the needed info.

**Comment by leigh123linux** [comment]
Does this issue affect any 64bit installs?

**Comment by jonathonf** [comment]
Yes, the trace above is from a 64-bit OS. However, it wasn't built in a clean build environment..

**Comment by leigh123linux** [comment]
I had to build xplayer* packages for my F30 install as I no longer include it in fedora, there are better players.
Build options used https://src.fedoraproject.org/rpms/xplayer/blob/f29/f/xplayer.spec#_118
I've played several mkv files and altered subtitle settings andcan't reproduce the issue.

P.S sorry for the pre-coffee mood earlier, fedora pre-release is a very busy time here since I handle rpmfusion release engineering tasks in addition to my normal load.

**Comment by leigh123linux** [comment]
I have a assertion warning for gstreamer, maybe gstreamer switch to using meson for build has exposed an issue in Manjaro's packaging of it?



https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/NGTKAANZBGMY5MM6EXZQSRGUT33NNJWX/

```
(xplayer:3476): GStreamer-CRITICAL **: 10:14:52.373: gst_tag_list_get_string_index: assertion 'GST_IS_TAG_LIST (list)' failed
```

**Comment by leigh123linux** [comment]
FTR Fedora still uses autotools for gstreamer1*.

Is  Manjaro's packaging similar to Archlinux?

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gstreamer

**Comment by jonathonf** [comment]
Manjaro uses Arch as upstream for the majority of its packages, so in this case it uses a Manjaro-specific [PKGBUILD for xplayer](https://gitlab.manjaro.org/packages/community/x-apps/xplayer) (I think based on the [AUR package](https://aur.archlinux.org/packages/xplayer)) along with the Arch gstreamer package.

While it looks like the switch to `meson` may have disabled asserts which xplayer relies on (?), I'm not sure that they should be enabled:

```
option('glib-asserts', type : 'feature', value : 'enabled', yield : true,
       description: 'Enable GLib assertion (auto = enabled for development, disabled for stable releases')
```

https://github.com/GStreamer/gstreamer/blob/ab60a330db717d452d995b7338cb17bc7b5fa94e/meson_options.txt#L37

**Comment by jojopara** [comment]
Hello,

I shall also make a comment howqever unknowledgeable I am.  I am a Manjaro user and had the same problem a few weeks ago.  Xplayer crashes the moment a video starts to play.

I have just re-installed Manjaro with clean install, formatting even the home directory.  For some time, Xplayer did what was expectef from it.  As I was completing my installation of various software, the plaer stopped working.  I was hoping to notice which and what caused it, but I missed it.

I hope this will help.

**Comment by leigh123linux** [comment]
Perhaps the registry got corrupted by the update, see

https://bugzilla.rpmfusion.org/show_bug.cgi?id=5247#c9

**Comment by oberon-manjaro** [comment]
In my case removing the registry didn't help.
```
$ gst-inspect-1.0 --plugin libav |grep -e 264 -e Version -e features -e elements -e typefinders
  Version                  1.16.0
  avenc_flashsv2: libav Flash Screen Video Version 2 encoder
  avenc_h264_omx: libav OpenMAX IL H.264 video encoder encoder
  avdec_h264: libav H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 decoder
  avmux_ipod: libav iPod H.264 MP4 (MPEG-4 Part 14) muxer
  600 features:
  +-- 576 elements
  +-- 24 typefinders
```

**Comment by alr888rav** [comment]
Same problem, mkv not played. I am rebuild player from AUR sources, didn't help.
ps Manjaro

**Comment by djsutton** [comment]
Arch AUR user here, and I'm able to reproduce with the same stack trace as @jonathonf.

I never got to the bottom of why the problem is only seen with AUR and Manjaro , but it looks like a fairly innocuous fix to check for NULL and avoid the segfault in update_orientation_from_video() in bacon-video-widget.c.  I have a pull request which fixes the issue at https://github.com/linuxmint/xplayer/pull/150.

I also posted a comment on AUR with instructions on a way to patch the AUR build immediately until a fix makes it in to a release here. I'm not sure what the right procedure is for an immediate Manjaro fix.

I'm not sure if there's a desire to keep bacon-video-widget.c in sync with the same file from totem, but from what I can tell, the totem version would also be vulnerable to the same bug

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/xplayer/pull/150
